# Site settings
title: Adrianna Jasińska 
description: Digital Marketing Specialist
# baseurl: "" # the subpath of your site, e.g. /blog
url: "https://gomarketing.beauty" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Adrianna Jasińska 
user_description: I'm junior digital marketing specialist with specific interest in beauty industry. 
user_title: Digital Marketing Specialist 
email: marketing.adriannajasinska@gmail.com
# twitter_username: lorem_ipsum
instagram_username: adriannajasinska 
# facebook_username: mauricio.urraco
# linkedin_username: murraco
# github_username:  adriannajasinska
# medium_username: lorem_ipsum
# medium_url: lorem_ipsum.medium.com
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src', 'node_modules', 'vendor']

